title: Alejandro Puerta-Cuartas
email: alpuerta@eco.uc3m.es
url: "https://apuertac94.github.io"
github_username: apuertac94
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag 
header_pages:
  - cv.md
  - research.md
  - teaching.md
minima:
  show_footer_credits: false
  show_footer_links: false
footer_content: |
  <p><a href="mailto:{{ site.email }}">{{ site.email }}</a> | 
  <a href="https://github.com/{{ site.github_username }}">GitHub</a></p>
 
